
name: Android CI
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true

      - name: Ensure Gradle Wrapper (robust)
        shell: bash
        run: |
          set -e
          if [ -x "./gradlew" ] && [ -f "./gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "gradlew & wrapper jar already present."
            exit 0
          fi

          echo "Fetching Gradle 8.8 to generate wrapper (with retries)..."
          URL="https://services.gradle.org/distributions/gradle-8.8-bin.zip"

          # 重试 6 次：2s/5s/8s/12s/18s/25s 回退
          for i in 1 2 3 4 5 6; do
            if curl -L --fail --retry 6 --retry-all-errors --connect-timeout 20 --max-time 300 \
               -o /tmp/gradle.zip "$URL"; then
              break
            fi
            sleep $(( i==1 ? 2 : (i==2 ? 5 : (i==3 ? 8 : (i==4 ? 12 : (i==5 ? 18 : 25)))) ))
            echo "Retry #$i ..."
          done

          if [ ! -s /tmp/gradle.zip ]; then
            echo "❌ Failed to download Gradle distribution after retries."
            exit 1
          fi

          unzip -q /tmp/gradle.zip -d /tmp
          /tmp/gradle-8.8/bin/gradle -v
          /tmp/gradle-8.8/bin/gradle wrapper --gradle-version 8.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew



      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew --no-daemon --stacktrace clean assembleDebug


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
