name: Android CI
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 关键：把输出同时写入 build.log，方便失败后上传
      - name: Build (capture full log)
        run: |
          set -uo pipefail
          : > build.log
          ./gradlew --version                           2>&1 | tee -a build.log
          ./gradlew clean                              --no-daemon           2>&1 | tee -a build.log
          # 单独跑一遍资源任务，让 AAPT2 把真正的报错细节吐干净
          ./gradlew :app:processDebugResources -i --stacktrace --no-daemon    2>&1 | tee -a build.log
          # 再尝试完整打包
          ./gradlew assembleDebug --stacktrace --no-daemon                    2>&1 | tee -a build.log

      # 关键：即便失败也上传日志
      - name: Upload build.log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
          if-no-files-found: warn

      # 若有 APK 就一并传上来（没有也不报错）
      - name: Upload APK (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: warn
